services:
  backend:
    build:
      context: ./backend
      dockerfile: _Dockerfile
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DB: jdbc:postgresql://postgres:5432/marketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      IMAGE_UPLOAD_DIRECTORY: /images
      IMAGE_HOST_URL: http://host.docker.internal:8080
      SPRING_PROFILES_ACTIVE: production
      MAX_UPLOAD_SIZE_BYTES: 10000000
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://backend:8080
      NEXT_PUBLIC_BACKEND_API_VERSION: v1
    depends_on:
      - backend

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/postgres-data
      - ./db-init:/docker-entrypoint-initdb.d

volumes:
  postgres-data:
